version: 0.0
os: linux

files:
  - source: application/httpd.conf
    destination: /home/ec2-user/
  - source: .env
    destination: /home/ec2-user/


hooks:
  AfterInstall:
    - location: scripts/configure_wp.sh
      timeout: 500
      runas: root
