version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/codedeploy-data
  - source: /application/httpd.conf
    destination: /home/ec2-user/codedeploy-data-2


hooks:
  BeforeInstall:
    - location: scripts/configure_wp.sh
      timeout: 500
      runas: root
