version: 0.0
os: linux

files:
  - source: application/httpd.conf
    destination: /tmp/
  - source: .env
    destination: /tmp/


hooks:
  BeforeInstall:
    - location: scripts/configure_wp.sh
      timeout: 500
      runas: root
