version: 0.0
os: linux

files:
  - source: /.env
    destination: /home/ec2-user/codedeploy-data


hooks:
  BeforeInstall:
    - location: scripts/configure_wp.sh
      timeout: 500
      runas: root
