version: 0.0
os: linux

#Move configuration files on proper path in host machine
files:
  - source: .env
    destination: /home/ec2-user/
  - source: application/httpd.conf
    destination: /etc/httpd/conf/
  - source: application/wp-config.php
    destination: /var/www/html/
file_exists_behavior: OVERWRITE


#Run script to configure wordpress
hooks:
  AfterInstall:
    - location: scripts/configure_wp.sh
      timeout: 500
      runas: root
