version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ec2-user/codedeployscripts


hooks:
  BeforeInstall:
    - location: scripts/configure_wp.sh
      timeout: 500
      runas: root
