# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION : "eu-west-1"
  S3_BUCKET  : ${{ vars.S3_BUCKET }} #bucket where to download artifact
  S3_BUCKET_CODEDEPLOY : ${{ vars.S3_BUCKET_CODEDEPLOY }} #bucket without slash
  ARTIFACT_NAME : artifact_1.0.0._${{github.run_number}}.zip
 
permissions:
      id-token: write
      contents: read
jobs:
  build:
    name: Build package and download to S3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::052195330873:role/github-action-manually-role
          role-session-name: GitHub_Action_Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Build artifact
        run: |
          zip -r ${{env.ARTIFACT_NAME}} application/ codedeploy_scripts/ appspec.yml

      - name: Upload artifact to S3 bucket
        run: |
          aws s3 cp ${{env.ARTIFACT_NAME}} ${{ env.S3_BUCKET }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::052195330873:role/github-action-manually-role
          role-session-name: GitHub_Action_Role
          aws-region: ${{ env.AWS_REGION }}
      - run: |
         aws deploy create-deployment --application-name Test_application --deployment-group-name test-deployment-group --s3-location bucket=${{env.S3_BUCKET_CODEDEPLOY}},bundleType=zip,key=${{env.ARTIFACT_NAME}} --ignore-application-stop-failures

